name: tests

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

# Cancel previous running if a new push is made
# Source: https://stackoverflow.com/a/72408109/123545
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and start dependencies
        run: |
          brew install docker
          brew install qemu
          brew install colima
          # https://github.com/abiosoft/colima/issues/424#issuecomment-1335912905
          colima delete
          colima start --arch x86_64

      - name: Run Typesense
        run: |
          mkdir $(pwd)/typesense-data
          docker run -p 8108:8108 \
            -d \
            -v$(pwd)/typesense-data:/data typesense/typesense:28.0 \
            --data-dir /data \
            --api-key=xyz \
            --enable-cors
        shell: bash

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: latest-stable

      - name: Run tests
        run: swift test
